@Andersoszkda
  I’m interested in ... I’m currently learning ...
’m looking to collaborate on ...
  How to reach me ...
   Pronouns: ...
  Fun fact: ...

<!---
Andersoszkda/Andersoszkda is a ✨ special ✨ repository because its `README.md` (this file) appears on your GitHub profile.
You can click the Preview link to take a look at your changes.
--->
//bancobradesco.com.br
enter
